package net.orangemile.informatica.powercenter.domain.constant;

public enum TimerType {	
	START_AT_ABSOLUTE_TIME,
	START_AT_ABSOLUTE_VARIABLE,
	START_RELATIVE_TO_PREVIOUSTASK,
	START_RELATIVE_TO_PARENT_WORKFLOW,
	START_RELATIVE_TO_TOPLEVEL_WORKFLOW
}